# conda env create -f environment.yml
# conda env export --no-builds > bioinf.yml
name: bioinf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.15
  - bioconda::multiqc=1.13
  - bioconda::fastqc=0.11.9
  - bioconda::star=2.7.10b
  - bioconda::samtools=1.16.1
  - bioconda::picard-slim=2.27.4
  - bioconda::salmon=1.9.0
  - bioconda::bedtools=2.30.0
